services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fake_news_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - app-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: fake_news_streamlit
    restart: unless-stopped
    ports:
      - "8502:8502"
    environment:
      - API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
