services:
  backend:
    build: .
    container_name: fake_news_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: fake_news_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
